package edu.auburn.comp6360.network;

import java.io.Serializable;

public class Packet implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -5088013409407823196L; 	// Automatically generated by Eclipse
	private PacketHeader header;
	private VehicleInfo vInfo;
	
//	private int packetSize;
	
	public Packet() {
		
	}
	
	public Packet(PacketHeader header, VehicleInfo vInfo) {
		this.header = header;
		this.vInfo = vInfo;
	}
	
	public void setHead(PacketHeader header) {
		this.header = header;
	}
	
	public void setVehicleInfo(VehicleInfo vInfo) {
		this.vInfo = vInfo;
	}

	
	public PacketHeader getHeader() {
		return this.header;
	}
	
	public VehicleInfo getVehicleInfo() {
		return this.vInfo;
	}
	
	public int getPacketSize() {
		return 4096;
	}
	
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("source: " + this.getHeader().getSourceID() + ", ");
		sb.append("sn: " + this.getHeader().getSeqNum() + ", ");
		sb.append(this.getVehicleInfo().toString());
		return sb.toString(); 
	}
	
}
