package edu.auburn.comp6360.network;

import java.io.Serializable;

public class Packet implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -5088013409407823196L; 	// Automatically generated by Eclipse
	private Header header;
	private VehicleInfo vInfo;
	
//	private int packetSize;
	
	public Packet(Header header) {
		this.header = header;
		this.vInfo = null;
	}

	public Packet(Header header, VehicleInfo vInfo) {
		this.header = header;
		this.vInfo = vInfo;
	}
	
	public void setHeader(Header header) {
		this.header = header;
	}
	
	public void setVehicleInfo(VehicleInfo vInfo) {
		this.vInfo = vInfo;
	}

	
	public Header getHeader() {
		return this.header;
	}
	
	public VehicleInfo getVehicleInfo() {
		return this.vInfo;
	}
	
	public int getPacketSize() {
		return 4096;
	}
	
	public String toString() {
		StringBuffer sb = new StringBuffer();
//		sb.append("source: " + this.getHeader().getSource() + ", ");
		Header header = this.getHeader();
		sb.append(header.getPacketType() + " " + header.getSeqNum() + ", from " + header.getSource() + ".\t");
		if (!(header.getPacketType().equals("normal")))
			sb.append("Piggybacked info: " + header.getPiggyback() + ".\t");
		if (this.getVehicleInfo() != null)
			sb.append(this.getVehicleInfo().toString());
		return sb.toString(); 
	}
	
}
